### ISSUE TITLE
READMEから連絡先を落とす

### ISSUE THREAD

**Issue by kanebako** [moneyforward/api-doc#59]
https://github.com/moneyforward/api-doc/blob/master/README.md
から連絡先の項目を落として頂けますでしょうか

**Comment by sawadatsuyoshi-mf** [comment]
@kanebako  https://moneyforward.slack.com/archives/C38438PCL/p1516172117000012

**Comment by kanebako** [comment]
@sawadatsuyoshi-mf ダメではないと思います。自分は特にウィルはないです

**Comment by sawadatsuyoshi-mf** [comment]
ページをまとめる方向で修正します。

**Comment by sawadatsuyoshi-mf** [comment]
完了しました。https://github.com/moneyforward/api-doc/pull/60
